platform :ios, '18.2'

use_frameworks! :linkage => :static

target 'iosApp' do
    pod 'composeApp', :path => '../composeApp'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.2'
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
        end
    end
end